### PR TITLE
Update MyArrayList.java

### PR DESCRIPTION
**Pull request by techdevg**
Added some comments to file for better understanding.

### CODE REVIEW

**Comment by Anuj-Kumar-Sharma** [comment]
@techdevg please resolve conflicts

**Comment by techdevg** [comment]
@Anuj-Kumar-Sharma  Done :)

**Comment by Anuj-Kumar-Sharma** [comment]
Hi @techdevg, Please put the comment on a separate line then the code. Always put your comments above the code line, that way you will not be taking the responsibility for the code itself.

**Comment by techdevg** [comment]
Thanks @Anuj-Kumar-Sharma for the guidance. I've done it.

**Comment by techdevg** [comment]
Done bhaiya!!
Please reply on Instagram(@realdev2000), it's very urgent bhaiya. I'm going
to pursue my 5th sem of BCA course and I've not much time.
Thank you!
regards Dev Kumar

**Pull request closed without merging**
